#pragma once

#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "PCSPPersonaCache.generated.h"

/**
 * Loads and caches pre-projected 64-dim persona embeddings from
 * Content/PCSP/Data/persona_embeddings.json (generated by export_pcsp_onnx.py).
 *
 * Persona IDs are 1-based; index into Embeddings[] = ID - 1.
 */
UCLASS()
class CNZOI_API UPCSPPersonaCache : public UObject
{
	GENERATED_BODY()

public:
	bool LoadFromFile(const FString& AbsPath);

	/**
	 * Loads persona_texts.json (exported from research/data/personas). Optional:
	 * the policy runs on embeddings alone, this is only for HUD presentation.
	 */
	bool LoadTextsFromFile(const FString& AbsPath);

	bool IsLoaded() const { return bLoaded; }

	/** Authored description for a 1-based persona ID; empty when unavailable. */
	const FString& GetPersonaText(int32 PersonaId) const;

	/** "occupation, age" for a 1-based persona ID; empty when unavailable. */
	const FString& GetPersonaSubtitle(int32 PersonaId) const;

	// Returns the 64-dim projected embedding for a 1-based persona ID.
	// Returns an empty view if ID is out of range.
	TConstArrayView<float> GetEmbedding(int32 PersonaId) const;

	int32 NumPersonas()  const { return Embeddings.Num(); }
	int32 PersonaDim()   const { return CachedPersonaDim; }
	int32 ObsDim()       const { return CachedObsDim; }
	int32 NumActions()   const { return CachedNumActions; }

private:
	// Flat storage: Embeddings[i] contains PersonaDim floats for persona (i+1).
	TArray<TArray<float>> Embeddings;

	// Parallel to Embeddings; index i holds the text for persona (i+1).
	TArray<FString> PersonaTexts;
	TArray<FString> PersonaSubtitles;

	int32 CachedPersonaDim  = 64;
	int32 CachedObsDim      = 33;
	int32 CachedNumActions  = 20;
	bool  bLoaded           = false;
};
