#pragma once

#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "PCSPPersonaCache.generated.h"

/**
 * Loads and caches pre-projected 64-dim persona embeddings from
 * Content/PCSP/Data/persona_embeddings.json (generated by export_pcsp_onnx.py).
 *
 * Persona IDs are 1-based; index into Embeddings[] = ID - 1.
 */
UCLASS()
class CNZOI_API UPCSPPersonaCache : public UObject
{
	GENERATED_BODY()

public:
	bool LoadFromFile(const FString& AbsPath);

	bool IsLoaded() const { return bLoaded; }

	// Returns the 64-dim projected embedding for a 1-based persona ID.
	// Returns an empty view if ID is out of range.
	TConstArrayView<float> GetEmbedding(int32 PersonaId) const;

	int32 NumPersonas()  const { return Embeddings.Num(); }
	int32 PersonaDim()   const { return CachedPersonaDim; }
	int32 ObsDim()       const { return CachedObsDim; }
	int32 NumActions()   const { return CachedNumActions; }

private:
	// Flat storage: Embeddings[i] contains PersonaDim floats for persona (i+1).
	TArray<TArray<float>> Embeddings;

	int32 CachedPersonaDim  = 64;
	int32 CachedObsDim      = 33;
	int32 CachedNumActions  = 20;
	bool  bLoaded           = false;
};
